# Generated by Django 4.2.2 on 2023-06-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_user_otp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_otp',
            name='otp',
            field=models.IntegerField(max_length=6),
        ),
    ]
