# Generated by Django 4.2.2 on 2023-07-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_user_otp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_otp',
            name='otp',
            field=models.IntegerField(),
        ),
    ]
